### ISSUE TITLE
Error on npm >5?

### ISSUE THREAD

**Issue by gsklee** [expo/xde#121]
Why does the XDE refuse to run with npm >5? I'm using Yarn and the version of npm means nothing to me.

**Comment by brentvatne** [comment]
XDE still works but it just warns you because we don't know how to determine if you're using yarn or npm reliably, and using npm5 will almost certainly break the app so we err on the side of warning for npm5. We're open to ideas for how we can reliably detect if someone is using yarn.

- We could check for yarn.lock but that wouldn't apply when you first create a project
- We could ask you, but then we'd need to expose an option for it that you could change later

Ideally, npm5 would just be fixed soon or marked as beta again and we don't have to deal with any of these warnings.

**Comment by gsklee** [comment]
Actually, what I am seeing now (in v2.19.1) is a hard error that completely prevented me from starting up the packaging server:

![https://i.imgur.com/v2P9wZV.png](https://i.imgur.com/v2P9wZV.png)

![https://i.imgur.com/oTZOJXO.png](https://i.imgur.com/oTZOJXO.png)

It shouldn't be like this. Should be a soft warning only.

**Comment by brentvatne** [comment]
@gsklee - I think the errors it's referring to are unrelated because I was able to start a project in XDE with 5.0.3. It does seem like it's missing any useful information about the actual errors there, so I agree that it looks like npm 5 is causing it. Can you try validating that exp/app.json and package.json are valid json? This is a pretty ugly looking bug if it's not surfacing an error for that

**Comment by gsklee** [comment]
Both package.json and app.json are valid JSON that passed JSON Lint; app.json was generated by CRNA.

**Comment by gsklee** [comment]
I updated to node 8 / npm 5 weeks ago and everything was working fine with XDE v2.18.0. I think there was indeed a JSON malformation warning but it's about a `package.json` further up my dependency tree, not my own `package.json`.

There's something in v2.19.0 or v2.19.1 that's causing this to become an XDE halting error.

**Comment by HeKnOw** [comment]
![image](https://user-images.githubusercontent.com/8148930/27620974-7c443c14-5b9b-11e7-99f9-68871a15b42b.png)
Same issue over here... I actually have tried changing the version of npm on my environment.. to 5.0.3 , the recommended 4.6.1 and 4.5.0... nothing worked. I will look into the malformed `package.json` somewhere in my dependencies like @gsklee and @brentvatne suggested. 

But this was not an issue until I updated to v.2.19.1

**Comment by HeKnOw** [comment]
**v2.19.2 fixes this issue.**.. did not see the release until after I posted... just thought I would post in case somebody like me goes straight for the issue 😜

**Comment by dikaiosune** [comment]
Looks like this was resolved in 2.19.2, sorry for the inconvenience here!
