### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by James2516** [expo/xde#147]
Seems like there's an update today that broke the log in.
When i try to log in through the website it gives https://i.imgur.com/i9ZdOor.png and redirect me to sign up.

When i try to log in through XDE it gives an error https://i.imgur.com/3AMQ8Q8.png even though i have filled up all the fields.

**Comment by cheneddie** [comment]
i get Same problen whit @James2516

**Comment by ide** [comment]
Our authentication provider had a database issue on their end that is currently being fixed so we've disabled login. In the meantime, if you use `exp` you can use the `--offline` flag to continue working on your project.

Once we hear our auth provider has fixed their problem (they're restoring from a backup) we'll restore some more account data to minimize data loss (hopefully have zero) and re-enable login. We don't have an ETA right now since we're waiting for our auth provider.

I'll be posting updates periodically in this forum post here: https://forums.expo.io/t/2017-10-25-issues-with-logging-into-expo-developer-accounts/4236/4.

**Comment by James2516** [comment]
I can't log in to the forums so i'm going to post here:
I'm still able to update my project through `exp publish`, and `exp build:android` worked occasionally.

**Comment by ide** [comment]
We believe the login & signup issues are fixed for nearly all developers. Try logging into the Expo website at https://expo.io/login first -- once you're able to log in there, then log into XDE or exp on your computer. Really sorry about the interruption and the stress this might have caused.

**Comment by brentvatne** [comment]
🙏
