### ISSUE TITLE
Unable To Create Project due to 60 second timeout

### ISSUE THREAD

**Issue by mssio** [expo/xde#153]
I am unable to create project using Expo XDE on my Mac.

The download timeout for creating a new project is too fast (60 seconds). I think you should change it to at least 600 seconds. My internet is fast enough (more than 500 KB/s download), a lot of people around the world will have internet that is much slower than mine.

When the download is more than 50% and it timeout, it retries from beginning again, so I will never be able to finish the download.

**Comment by brentvatne** [comment]
cc @fson / @charlesvinette

**Comment by charlesvinette** [comment]
Hi @mssio! Thanks for the feedback, we will have a look and get back to
you. Have a good sunday!

**Comment by agrawalo** [comment]
Originally reported by Lokesh Agrawal as part of this stack overflow question https://stackoverflow.com/questions/47377240/expo-xde-timeout-of-60000-ms-exceeded

**Comment by sumanta-ghosh** [comment]
I also face the same issue

**Comment by manikjain** [comment]
Facing the same issue as well while trying to create a new project. It repeatedly says, 'timeout of 60000ms exceeded'.

**Comment by rokob** [comment]
I hacked my way around this because it was extremely frustrating:

* The URL for the tab project data is at https://s3.amazonaws.com/exp-starter-apps/tabs-23.0.0.tar.gz (you can figure this out by using the console inside the electron app that is xde)
* Hit that URL in your web browser to download the file
* Edit /etc/hosts to point s3.amazonaws.com to localhost
* Run a web server on local host that serves that file when the url `/exp-starter-apps/tabs-23.0.0.tar.gz` is requested

Note that the request is being made over HTTPS so your local server will need to have a cert from a CA that identifies your server as being s3.amazonaws.com, but that is easy enough via the mac keychain to create a new CA and issue your own self-signed certs.

**Comment by serranoarevalo** [comment]
Any fix for this?

**Comment by fson** [comment]
I've published an update to XDE that increases the timeout. If you continue to see the problem after upgrading to XDE v2.22.1, please let us know.
