### ISSUE TITLE
Exponent App in Android not handling exp:// protocol URLs

### ISSUE THREAD

**Issue by cpb** [expo/xde#44]
#### Expected

Clicking `exp://` links opens exponent app
#### Actual

`exp://` omitted from clickable portion of text message, serves json over http instead.

**Comment by cpb** [comment]
Seems it is the smsed exp.direct url that wasn't working. I see the example once I publish to exp.host.

**Comment by ide** [comment]
@cpb Thanks for the bug report. Just to clarify, your text message app linkified the domain + path part of the URL, but not the `exp://` protocol and therefore treated it as an HTTP link?

We plan to improve this problem with this approach:
- In the short-term, we'll make XDE check your user-agent string to see if you're opening the link from Chrome instead of Exponent, in which case we'll serve a helpful HTML page that lets you redirect to Exponent.
- Longer-term (this requires a change to the Exponent client app), we'll switch to using `http://` instead of `exp://` and make Android give you the option to open `http://*.exp.direct` links in Exponent instead of Chrome. That way your SMS app (or some other app) has to only know how to linkify `http://` URLs and everything should work.

For now, I recommend copying the URL to your clipboard (on your phone) and then pasting it into Exponent itself (pull down on the main screen to reveal a URL bar). It's a little less convenient but should get you unblocked.

**Comment by cpb** [comment]
> @cpb Thanks for the bug report. Just to clarify, your text message app linkified the domain + path part of the URL, but not the exp:// protocol and therefore treated it as an HTTP link?

Correct!

> For now, I recommend copying the URL to your clipboard (on your phone) and then pasting it into Exponent itself (pull down on the main screen to reveal a URL bar). It's a little less convenient but should get you unblocked.

I tried that, then got into #43 ! :-)
