### ISSUE TITLE
Login fails with self-signed security certificate.

### ISSUE THREAD

**Issue by thebetterjort** [expo/xde#85]
Cannot login. 
I get an unknown error if I try and login through a regular sign in. I get  Authenticated successfully! You can close this window. when I use git hub, but then it returns 0: in red.

I believe this has to do with our self-signed security certificate. Please advise on how to disable SSL checks?

**Comment by jesseruder** [comment]
Please don't open duplicate issues. An issue here or in the xdl repo is fine but just consolidate all of the information in one place.

**Comment by ide** [comment]
We don't offer a way to turn off HTTPS because the integrity of TLS affects the security integrity of other parts of Expo.

We are looking into making the Expo tools inherit the connection settings of Chromium/Electron when using XDE, which might address your issue (I'm assuming you have some networking hardware that intercepts HTTPS connections). We also support the standard environment variables `HTTP_PROXY` and `HTTPS_PROXY` -- those might also address your issue. In general though we don't plan to offer ways to decrease security in this way.

**Comment by thebetterjort** [comment]
Great thank you. This isn't a proxy server that can be set by environmental variables. It's as you said a hardware product. Unfortunately, at a company my size nearly 100 times Facebook I don't have all the power to make loopholes in our server.
