### ISSUE TITLE
adding flow config to new project

### ISSUE THREAD

**Issue by kkganesan** [expo/xde#95]
@brentvatne looks like there is no flow config file generated for project created using xde whereas there is one created using create-react-native command line. 
Thoughts ?

**Comment by ide** [comment]
Keeping the flowconfig up to date takes more work than might be expected since RN changes a lot and we can't commit to it right now. Adding a flowconfig to a project is easy if someone has one that's up to date and maintained, so if someone wanted to make a repo with a maintained flowconfig then people who want Flow could easily get the config. It's just something that the community & people interested in Flow are best set up to provide.
